Start Drinking On (SDO) company time
RIT-EVT/EVT-core pull request #112
Opened 2024-12-03 02:05 UTC by DiegoLHendrix

2024-12-14 16:06 UTC, mjh9585 requested changes
Just a few changes, mostly should make a method to register a callback that is used by the sdo.

2025-01-15 23:58 UTC, mjmagee991 requested changes
A good start

2025-01-15 23:58 UTC, mjmagee991 commented on src/core/io/CANopen.cpp
> +void registerCallBack(void (*AppCallback)(CO_CSDO* csdo, uint16_t index, uint8_t sub, uint32_t code),
What is the point of this function? Why not just pass the actual values in directly?

2025-01-15 23:58 UTC, mjmagee991 commented on src/core/io/CANopen.cpp
> +     * @param csdo[in] is the client-SDO object.
Don't vaguely follow the Doxygen standard for something like this because it makes it seem like you're trying to define a function

2025-01-15 23:58 UTC, mjmagee991 commented on samples/canopen/canopen_sdo/SDOCanNode.hpp
> +            .Data = (CO_DATA) 1,
It would be great to have macros for these

2025-01-15 23:58 UTC, mjmagee991 commented on samples/canopen/canopen_sdo/main.cpp
> +        queue->append(message);
```suggestion
    if (queue != nullptr) {
        queue->append(message);
    }
```

2025-01-15 23:58 UTC, mjmagee991 commented on samples/canopen/canopen_sdo/main.cpp
> +            testCanNode.receiveData(canNode);               // Receive data from server
I really do not like that you have to pass the CO_NODE in every time you call this function. I think it might be better to store the CO_NODE in SDOCanNode, but I'm not sure because you'd have to make a function to get a pointer to pass into `io::processCANopenNode`. @mjh9585 what do you think?

2025-01-15 23:58 UTC, mjmagee991 commented on src/core/io/CANopen.cpp
> +void (*callback)(CO_CSDO* csdo, uint16_t index, uint8_t sub, uint32_t code);
I left another comment about possible getting rid of these. If you do end up keeping them, you need to add more documentation to explain them

2025-01-16 23:22 UTC, DiegoLHendrix commented on include/core/io/CANOpenMacros.hpp
> +        .Key  = CO_KEY(0x1200, 0x01, CO_OBJ_DN__R_),    \
The D makes it so the actual value is accessed instead of just a pointer to it.

2025-01-18 15:29 UTC, mjh9585 commented on include/core/io/CANopen.hpp
>  namespace core::io {
I would agree with that. It will be a breaking change but can be rolled into a 2.0 release as one of the major changes.

2025-01-18 15:45 UTC, mjh9585 commented on samples/canopen/canopen_sdo/main.cpp
> +            testCanNode.receiveData(canNode);               // Receive data from server
I think it is fine as you still have to pass it into `io::processCANopenNode` and an extra method to access CO_NODE from SDOCanNode would make it harder to follow. Perhaps a better approach would be to pass a pointer to CO_NODE into the constructor instead.

2025-01-18 15:46 UTC, DiegoLHendrix commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +     * sub-index 0x02. Registers and executes the SDOTransferCallback function upon completion.
This is required. The entry is a parameter in the SDO download and upload functions in CANopen.cpp line 161 and 188.

2025-01-18 17:10 UTC, DiegoLHendrix commented on include/core/io/CANopen.hpp
> +void AppCSdoTransferCb(CO_CSDO *csdo, uint16_t index, uint8_t sub, uint32_t code);
Code is an error code assigned when the transfer or receive operation finalizes.

2025-02-22 15:34 UTC, mjh9585 commented on include/core/io/CANopen.hpp
>  namespace core::io {
For now you can leave this

2025-02-22 18:49 UTC, mjh9585 requested changes
Just a couple of changes. Make sure to clean up leftover code from the unresolved comments.

2025-02-22 18:49 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +    core::io::registerCallBack(AppCallback, reinterpret_cast<void*>(csdo)); // Register callback function
If you are registering a global callback you should probably not be registering it in this method.

2025-02-22 18:49 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +    context  = AppContext;
How are you passing this context into the callback? You need some other method to apply the context to your callback.

2025-05-24 17:31 UTC, mjmagee991 approved these changes

2025-06-07 15:31 UTC, mjh9585 requested changes
A couple of changes. I noticed a lot of resolved comments that didn't seem to have anything changed for them, did you forget to push something? I marked them as unresolved and left a comment on most of them.

2025-06-07 15:31 UTC, mjh9585 commented on include/core/io/CANOpenMacros.hpp
> +    }
This macro should take in a NodeID of device's server you want to talk to. This should then set sub-index 3 to that value. Additionally, your comment for sub-index 3 is the same as 2 and should instead be "Node-ID of the SDO server". Check https://canopennode.github.io/CANopenSocket/md_example_DS301_profile.html for the 1280 key.

2025-06-07 15:31 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> +namespace log = core::log;
Logging is still included in the hpp file.

2025-06-07 15:31 UTC, mjh9585 commented on samples/canopen/canopen_rpdo/main.cpp
> +    snprintf(&messageString[5],
Why do you start at index 5 of your string? This could start your string with random characters or terminate it before you print anything. Also why do you specify a string length of 6 when you clearly have a longer string?

2025-06-07 15:31 UTC, mjh9585 commented on samples/canopen/canopen_rpdo/main.cpp
> +        snprintf(&messageString[i * 5], 1, "%X ", *data);
Same here, your length is 1 character, but your string is multiple characters? Also your string isn't a fixed length so you can't assume that `i*5` will not overwrite something. possibly `&messageString[strlen(messageString)]` would be better.

2025-06-07 15:31 UTC, mjh9585 commented on samples/canopen/canopen_rpdo/main.cpp
> +
You should wrap all of these debug formats with an #if to only preform the formatting if logging is enabled.

2025-06-07 15:31 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +    transferBuffArray[1] = 0;
Is there a reason this isn't an initialization list?

2025-06-07 15:31 UTC, mjh9585 commented on samples/canopen/canopen_tpdo/main.cpp
> +#include <string>
You want `<cstring>` instead.

2026-03-30 06:08 UTC, mjh9585 requested changes
Overall pretty good, just needs a few changes and a little polish. Also you never take advantage of your blocking methods in your sample which could be helpful to see an example for simple use cases.

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +    static uint8_t receiveBuffArray[1];
This is allocated on the stack in this function but `SDOReceive` is asynchronous an will be an invalid memory location by the time you receive the data. Move this to a member variable of the class.

2026-03-30 06:08 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + */
```suggestion
/**
 * This function starts an asynchronous SDO download (write) request to transfer data
 * to the specified object dictionary entry on the target CANopen node.
 *
 * @param node[in]             Reference to the CANopen node object
 * @param data[in]             Pointer to the data buffer that holds the data to send
 * @param size[in]             Size of the data to transfer in bytes
 * @param entry[in]            Object dictionary entry (index + subindex) to write to
 * @param transferCallback[in] Callback function for the transfer operation
 * @param transferContext[in]  Context for the callback function
 * @return CO_ERR[out]         Returns the result of scheduling the transfer operation
 */
```

2026-03-30 06:08 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + */
```suggestion
/**
 * This function starts an asynchronous SDO upload (read) request to fetch data from 
 * the specified object dictionary entry on the target CANopen node
 *
 * @param node[in]            Reference to the CANopen node object
 * @param data[in]            Pointer to the buffer where received data will be stored
 * @param size[in]            Size of the buffer provided to receive data
 * @param entry[in]           Object dictionary entry (index + subindex) to read from
 * @param receiveCallback[in] Callback function for the receive operation
 * @param receiveContext[in]  Context for the callback function
 * @return CO_ERR[out]        Returns the result of scheduling the receive operation
 */
```

2026-03-30 06:08 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + */
```suggestion
/**
 * This function performs a blocking  SDO download (write) request to transfer data to the
 * specified object dictionary entry on the target CANopen node and waits for the response.
 *
 * @param node[in]        Reference to the CANopen node object
 * @param data[in]        Pointer to the data buffer that holds the data to send
 * @param size[in]        Size of the data to transfer in bytes
 * @param entry[in]       Object dictionary entry (index + subindex) to write to
 * @return CO_ERR[out]    Returns the result of the transfer operation
 */
```

2026-03-30 06:08 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + */
```suggestion
/**
 * This function performs a blocking SDO upload (read) request to fetch data from
 * the specified object dictionary entry on the target CANopen node.
 *
 * @param node[in]        Reference to the CANopen node object
 * @param data[in]        Pointer to the buffer where received data will be stored
 * @param size[in]        Size of the buffer provided to receive data
 * @param entry[in]       Object dictionary entry (index + subindex) to read from
 * @return CO_ERR[out]    Returns the result of the receive operation
 */
```

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/main.cpp
> +        snprintf(&messageString[0], 25, "Value transferred %x, %x\r\n", csdo->Tfer.Buf[0], csdo->Tfer.Buf[1]);
Since this is a sample, it may be better to show the use of context by passing in your variable that the value is stored in rather than accessing the canopen object. Likewise, since this is the transfer callback, this data isn't really that useful since you are sending it. A better use of this callback would be to detect errors with s simple message that prints out if there is an issue.

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/main.cpp
> +        snprintf(&messageString[0], 25, "Value received %x, %x\r\n", csdo->Tfer.Buf[0], csdo->Tfer.Buf[1]);
Since this is a sample, it may be better to show the use of context by passing in your variable that the value is stored in rather than accessing the canopen object.

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.hpp
> +    uint16_t sampleDataB;
You are not really using these values in your sample, are you able to use them for your transfer and receive somehow instead of a raw array?

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.hpp
> +        DATA_LINK_21XX(0x00, 0x02, CO_TUNSIGNED16, &sampleDataB),
Are you using these entries?

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +    CO_ERR err = core::io::SDOReceive(node, receiveBuffArray, 1, CO_DEV(0x2100, 0x01), callback, context);
Maybe pass the variable you are using to hold the response in as a context so you callback can do something with the variable.

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +    CO_ERR err = core::io::SDOTransfer(node, transferBuffArray, 2, CO_DEV(0x2100, 0x02), callback, context);
Does this have any use for the context in your sample?

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +        /* Note: don't use the 'readValue' until transfer is finished! */
What do you mean by the "readValue"?

2026-03-30 06:08 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +        /* Note: don't use the 'readValue' until transfer is finished! */
What do you mean by the "readValue"? Also "transfer" is a little confusing here since this uses the receive method and we have a method called `SDOTransfer`.

2026-03-30 06:08 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +        time::wait(100);
I would be careful about putting such a long wait here as it may be unexpected for this to take so long. A defined constant would be good to put here and if it is set to 0 just immediately return with an error.

2026-03-30 06:08 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +        err = COCSdoRequestDownload(csdo, entry, data, size, internalCallback, 1000);
Use a define!

2026-03-30 06:08 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +CO_ERR SDOReceive(CO_NODE& node, uint8_t* data, uint8_t size, uint32_t entry, csdo_callback_t receiveCallback,
Same comments as `SDOTransfer`

2026-03-30 06:08 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +        return CO_ERR_SDO_ABORT;
Return `lastErr` so we know what happened.

2026-03-30 06:08 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +CO_ERR SDOReceiveBlocking(CO_NODE& node, uint8_t* data, uint8_t size, uint32_t entry) {
Same comments as `SDOTransferBlocking`.

2026-03-30 06:08 UTC, mjh9585 commented on src/core/io/CANopen.cpp
> +        time::wait(100);
Define!

2026-04-06 19:29 UTC, DiegoLHendrix commented on samples/canopen/canopen_sdo/SDOCanNode.hpp
> +    uint16_t sampleDataB;
For the transfer operation I could increment their value and assign that to the arrays, but for receiving I don't see a use case because the context is what is holding the received value

2026-04-06 19:32 UTC, DiegoLHendrix commented on samples/canopen/canopen_sdo/SDOCanNode.hpp
> +        DATA_LINK_21XX(0x00, 0x02, CO_TUNSIGNED16, &sampleDataB),
As of right now no, I think it'd be better to delete these entries and the variables instead. Thoughts?

2026-04-13 23:52 UTC, aclowmclaughlin approved these changes
Looks good. Minor stuff and obviously you're going to need to test it.
Approving, pending a demonstrated test setup working.

2026-04-13 23:52 UTC, aclowmclaughlin commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +    /* Increment the first element of transferBuffArray by 1. */
Why are we doing any of this?
These comments describe what we are doing but not why

2026-04-13 23:52 UTC, aclowmclaughlin commented on samples/canopen/canopen_sdo/SDOCanNode.hpp
> + * Representation of the CAN node. Handles constructing the object
Would like a more detailed explanation for the SDO CAN node specifically.

2026-04-21 01:25 UTC, mjh9585 approved these changes
Looks good, just need some formatting fixes,

2026-04-21 01:25 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + * @param data[in]            Pointer to the buffer where received data will be stored
nit
```suggestion
 * @param data[out]            Pointer to the buffer where received data will be stored
```

2026-04-21 01:25 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + * @return CO_ERR[out]         Returns the result of scheduling the transfer operation
nit
```suggestion
 * @return CO_ERR         Returns the result of scheduling the transfer operation
```

2026-04-21 01:25 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + * @return CO_ERR[out]        Returns the result of scheduling the receive operation
nit
```suggestion
 * @return CO_ERR           Returns the result of scheduling the receive operation
```

2026-04-21 01:25 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> + * @param data[in]        Pointer to the buffer where received data will be stored
nit
```suggestion
 * @param data[out]        Pointer to the buffer where received data will be stored
```

2026-04-21 01:25 UTC, mjh9585 commented on include/core/io/CANopen.hpp
> +uint32_t SDOReceiveBlocking(CO_NODE& node, uint8_t* data, uint8_t size, uint32_t entry);
```suggestion
 * @param entry[in]       Object dictionary entry (index + subindex) to read from
 * @return CO_ERR         Returns the result of the receive operation
 */
uint32_t SDOReceiveBlocking(CO_NODE& node, uint8_t* data, uint8_t size, uint32_t entry);
```

2026-04-21 01:25 UTC, mjh9585 commented on samples/canopen/canopen_rpdo/main.cpp
nit
```suggestion
#include <cstdio>
#include <cstring>

#include <core/io/CANopen.hpp>
#include <core/io/UART.hpp>
#include <core/io/types/CANMessage.hpp>
#include <core/manager.hpp>
#include <core/utils/log.hpp>
#include <core/utils/time.hpp>
#include <core/utils/types/FixedQueue.hpp>

```

2026-04-21 01:25 UTC, mjh9585 commented on samples/canopen/canopen_sdo/SDOCanNode.cpp
> +#include <cstdio>
nit
```suggestion
#include "SDOCanNode.hpp"

#include <cstdio>

#include <core/utils/log.hpp>
```

2026-04-21 01:25 UTC, mjh9585 commented on samples/canopen/canopen_sdo/main.cpp
> +#include "SDOCanNode.hpp"
nit 
```suggestion
#include "SDOCanNode.hpp"

#include <cstdio>
#include <cstring>

#include <core/io/CAN.hpp>
#include <core/io/CANopen.hpp>
#include <core/io/types/CANMessage.hpp>
#include <core/io/UART.hpp>
#include <core/manager.hpp>
#include <core/utils/log.hpp>
#include <core/utils/time.hpp>
#include <core/utils/types/FixedQueue.hpp>
```

2026-04-21 01:25 UTC, mjh9585 commented on samples/canopen/canopen_tpdo/main.cpp
nit
```suggestion
#include <cstdio>
#include <cstring>

#include <core/io/CANopen.hpp>
#include <core/io/types/CANMessage.hpp>
#include <core/io/UART.hpp>
#include <core/manager.hpp>
#include <core/utils/log.hpp>
#include <core/utils/time.hpp>
#include <core/utils/types/FixedQueue.hpp>

```

2026-04-21 01:25 UTC, mjh9585 commented on src/core/io/CANopen.cpp
>  #include <stdint.h>
nit 
```suggestion
#include <core/io/CANopen.hpp>

#include <stdint.h>

#include <co_csdo.h>
#include <core/dev/RTC.hpp>
#include <core/io/CANDevice.hpp>
#include <core/io/types/CANMessage.hpp>
#include <core/utils/log.hpp>
#include <core/utils/types/FixedQueue.hpp>

```

2026-04-23 23:21 UTC, merged