Cleanup Cleanup Everybody Do Their Share
RIT-EVT/EVT-core pull request #48
Opened 2022-02-14 23:42 UTC by cbolles

Just some documentation cleanup

* Remove cpplint from project
* Update README for currently supported features
* Add STM32f334 to Sphinx documentation
* Change docstrings to use `@param[in] name` (correct) vs `param name[in]`

2022-02-14 23:50 UTC, zsteig approved these changes

2022-02-15 01:28 UTC, mjmagee991 requested changes
The cleanup is much appreciated. Just looks like you missed a line.

2022-02-15 01:28 UTC, mjmagee991 commented on include/EVT/dev/platform/f3xx/f302x8/Timerf302x8.hpp
>       * @param timerPeripheral[in]  The timer peripheral to configure.  Possible options for this board are
It looks like you missed this one

2022-02-15 01:29 UTC, cbolles commented on include/EVT/dev/platform/f3xx/f302x8/Timerf302x8.hpp
>       * @param timerPeripheral[in]  The timer peripheral to configure.  Possible options for this board are
nice catch

2022-02-15 14:28 UTC, merged