Polyamorous Building
RIT-EVT/EVT-core pull request #56
Opened 2022-03-19 16:44 UTC by mjmagee991

Added GitHub build testing for the F334

2022-03-22 15:53 UTC, cbolles approved these changes
Looks good!

2022-03-25 00:12 UTC, zsteig approved these changes

2022-03-25 00:28 UTC, cbolles requested changes
`-B` just specifies the build path, unfortunately it doesn't actually run the build. We might be able to do something like
```
mkdir build && cd build && cmake ../ -DTARGET_DEV=STM32F302x8 && make -j
```

2022-03-25 00:49 UTC, cbolles approved these changes
Looks good

2022-03-25 00:56 UTC, merged