CAN filter and Example TPDO Node ID
RIT-EVT/EVT-core pull request #65
Opened 2022-10-01 18:49 UTC by mjh9585

Fixed CAN filter and Corrected example TPDO to include Node ID

2022-10-01 18:54 UTC, mjh9585 commented
![](https://github.trello.services/images/mini-trello-icon.png) [CAN bus filter blocks all messages (5 Points)](https://trello.com/c/vnLQS86t/70-can-bus-filter-blocks-all-messages-5-points)

2022-10-01 21:02 UTC, AarC10 requested changes

2022-10-01 21:02 UTC, AarC10 commented on src/io/platform/f3xx/CANf3xx.cpp
> +    defaultFilter.FilterMaskIdHigh = 0x0000;
Comment on line 106 should reflect new changes if we are now accepting all messages.

2022-10-04 00:05 UTC, mjmagee991 approved these changes
Looks good

2022-10-24 05:28 UTC, merged