When the Time is Out
RIT-EVT/EVT-core pull request #72
Opened 2023-01-13 15:05 UTC by mjmagee991

Changed I2C and SPI Timeouts to be adjustable with a #define

2023-01-13 15:05 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix BQ Setting to UART Script](https://trello.com/c/o9mnRqDJ/103-fix-bq-setting-to-uart-script)

2023-01-18 04:02 UTC, AarC10 requested changes

2023-01-18 04:02 UTC, AarC10 commented on include/EVT/io/SPI.hpp
> +        read(uint8_t* bytes, uint8_t length);
I think some formatting is broken here

2023-01-20 00:23 UTC, zsteig approved these changes

2023-01-24 01:09 UTC, AarC10 approved these changes
Matt abuses his power

2023-01-24 01:11 UTC, merged