I too (2) can now see (C) multiple bytes
RIT-EVT/EVT-core pull request #75
Opened 2023-02-14 01:46 UTC by pro-sper

readReg() method modified for multibyte i2c reads

2023-02-14 01:49 UTC, pro-sper commented
![](https://github.trello.services/images/mini-trello-icon.png) [I2C Read Multiple Bytes](https://trello.com/c/wik1gcJI/120-i2c-read-multiple-bytes)

2023-02-16 22:53 UTC, mjmagee991 requested changes
A couple minor changes

2023-02-16 22:53 UTC, mjmagee991 commented on src/io/I2C.cpp
> +    I2C_RETURN_IF_ERR(write(addr, reg[0]));
This write call is only writing 1 byte of the register address. You should use the write override that writes multiple bytes

2023-02-16 22:53 UTC, mjmagee991 commented on src/io/I2C.cpp
> +    I2C_RETURN_IF_ERR(read(addr, &bytes[0], length));
```suggestion
    I2C_RETURN_IF_ERR(read(addr, bytes, length));
```
Deleting these characters doesn't actually change the behavior of this call. With the ampersand and brackets, you're passing the address of the first element in the array, which is what `bytes` already is

2023-02-21 00:45 UTC, mjmagee991 approved these changes
Nice

2023-02-21 00:48 UTC, ishan-renjen approved these changes

2023-02-21 00:48 UTC, ActuallyZach approved these changes

2023-02-21 00:48 UTC, merged