U ARen'T Reading the Documentation
RIT-EVT/EVT-core pull request #77
Opened 2023-03-03 22:44 UTC by mjmagee991

Enabled UART pin swapping

2023-03-03 23:05 UTC, jlb1854 commented
I'm glad we have the hardware in place to fix this issue. Thank you for implementing this software feature.

2023-03-03 23:09 UTC, jlb1854 approved these changes
Great work!

2023-03-04 04:39 UTC, jlb1854 requested changes
Is this the best implementation you can have? This may cause confusion as it affects the entire repository, can you pass this as an argument to the constructor in the same manner as the pins? You could also implement this as part of the switch case that determines which halUart object you are referencing with the pins passed to the constructor.

2023-03-04 15:30 UTC, ActuallyZach requested changes

2023-03-04 15:30 UTC, ActuallyZach commented on include/EVT/io/platform/f3xx/UARTf3xx.hpp
>       */
What does isSwapped do? There should be documentation for it.

2023-03-04 15:36 UTC, ActuallyZach approved these changes
Looks good!

2023-03-07 05:42 UTC, jlb1854 commented
Great job!

2023-03-07 05:42 UTC, jlb1854 approved these changes

2023-03-20 21:20 UTC, merged