✉️ Mail Forgery ✉️
RIT-EVT/EVT-core pull request #78
Opened 2023-03-23 23:42 UTC by ActuallyTaylor

Added a timeout in the HAL_CAN_GetTxMailboxesFreeLevel while loop. This allows us to overwrite the full mailboxes if there is no CAN network available.

2023-03-23 23:47 UTC, ActuallyTaylor commented
![](https://github.trello.services/images/mini-trello-icon.png) [CANOpen crash when not hooked up to a CAN network](https://trello.com/c/6Qiz5PhS/136-canopen-crash-when-not-hooked-up-to-a-can-network)

2023-03-23 23:53 UTC, Ethangirard62 approved these changes

2023-03-24 02:44 UTC, mjmagee991 requested changes
Documentation issue

2023-03-24 02:44 UTC, mjmagee991 commented on src/io/platform/f3xx/CANf3xx.cpp
> +    // Wait until mailbox 0 is available TODO: Add interrupt implementation
This comment should be updated

2023-03-27 23:06 UTC, DeLozM8 approved these changes

2023-04-22 18:10 UTC, merged