"🙏 Please Work" - Magee (PWM F4xx Support)
RIT-EVT/EVT-core pull request #95
Opened 2024-02-06 00:59 UTC by tmb5932

Added support for PWM on f4xx.

2024-02-09 00:51 UTC, mjh9585 approved these changes
Looks good! Just a few minor changes.

2024-02-09 00:51 UTC, mjh9585 commented on samples/pwm/main.cpp
> +    IO::PWM& pwm = IO::getPWM<IO::Pin::PC_8>();
Change the pin to one that is supported across all of the chips.

2024-02-09 00:51 UTC, mjh9585 commented on src/io/platform/f4xx/PWMf4xx.cpp
> + * is pulled from the STM32F446re documentation.
Capitalize "RE" in the part number

2024-02-09 04:23 UTC, mjmagee991 requested changes
Looks great! A couple minor details to iron out

2024-02-09 04:23 UTC, mjmagee991 commented on docs/source/api/stm32f3xx/stm32f3xx_io.rst
> +.. doxygenclass:: EVT::core::IO::PWMf4xx
```suggestion
.. doxygenclass:: EVT::core::IO::PWMf3xx
```

2024-02-09 04:23 UTC, mjmagee991 commented on include/EVT/io/platform/f4xx/PWMf4xx.hpp
> +    void setDutyCycle(uint32_t dutyCycle);
```suggestion
    void setDutyCycle(uint32_t dutyCycle) override;
```
Add this to all the public functions

2024-02-09 04:23 UTC, mjmagee991 commented on samples/pwm/main.cpp
Revert your changes to this file

2024-02-09 04:23 UTC, mjmagee991 commented on src/io/platform/f4xx/PWMf4xx.cpp
> +    HAL_TIM_PWM_Stop(&halTIM, halTIMChannelID);
Can you add this to PWMf3xx.cpp as well? Be sure to test that things still work after the change

2024-02-10 21:41 UTC, mjmagee991 approved these changes
Nice work

2024-02-13 00:10 UTC, merged